bk72xx:
  board: generic-bk7231t-qfn32-tuya
  framework:
    version: dev

logger:

web_server:

captive_portal:

mdns:

api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

button:
- platform: restart
  name: Restart

debug:
  update_interval: 30s

text_sensor:
- platform: debug
  reset_reason:
    name: Reset Reason
- platform: libretiny
  version:
    name: LibreTiny Version

sensor:
- platform: uptime
  name: Uptime

output:
- platform: ledc
  id: output_red
  pin: P26
- platform: ledc
  id: output_green
