substitutions:
  name: "plug-sbot"

esphome:
  name: "${display_name}"
  name_add_mac_suffix: true
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
  project:
    name: esphome.sbot-plug
    version: "1.0"

dashboard_import:
  package_import_url: github://zrhutto/esphome/sbot-plug.yaml@main
  import_full_config: false

esp32:
  variant: ESP32C3
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"    

logger:
api:
ota:

button:
  - platform: safe_mode
    name: ${display_name} (Safe Mode)

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #domain: !secret wifi_domain
  ap:
    ssid: "$display_name} Fallback"
    password: !secret wifi_ap_password

#  Disable the bluetooth tracker/proxy if they are not needed
esp32_ble_tracker:
  scan_parameters:
# Adjust timing if the defaults do not work in your environment
#    interval: 1100ms
#    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO20
      inverted: true
    cf_pin: GPIO18
    cf1_pin: GPIO19
    model: BL0937
    current_resistor: 0.0011
    voltage_divider: 1450
    current:
      name: ${display_name} Amps
    voltage:
      name: ${display_name} Volts
    power:
      name: ${display_name} Watts
      accuracy_decimals: 0       
    energy:
      name: ${display_name} Energy
    update_interval: 3s
    change_mode_every: 4

switch:
  - platform: gpio
    name: ${display_name} Relay
    id: relay
    device_class: outlet
    pin: GPIO6
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - light.turn_on: white_led
    on_turn_off:
      then:
        - light.turn_off: white_led  

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO2
      mode: INPUT_PULLUP
      inverted: true
    name: ${display_name} Button
    filters:
      - delayed_on: 10ms
    on_press:
      then:
        - switch.toggle: relay 

light:
  - platform: binary
    internal: true
    name: ${display_name} White LED
    id: white_led
    output: white_output
    restore_mode: RESTORE_DEFAULT_OFF

output:
  - id: white_output
    platform: gpio
    pin: GPIO7
    inverted: true

status_led:
  pin:
    number: GPIO8
    inverted: true
