substitutions:
  name: "plug"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "770"  
  update_time: 10s
  relay1RestoreMode: ALWAYS_ON
  relay2RestoreMode: ALWAYS_ON
  
esphome:
  name: "${name}"
  project:
    name: esphome.wyze-plug
    version: "1.1.1"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

dashboard_import:
  package_import_url: github://zrhutto/esphome/wyze-plug.yaml@main
  #import_full_config: true


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap: 
    ssid: ${name}_AP
    password: !secret wifi_ap_password
    ap_timeout: 3min
    
captive_portal:

logger:

api:

#mqtt:
#  broker: !secret mqtt_broker
#  username: !secret mqtt_user
#  password: !secret mqtt_pass

ota:

#web_server:

#  Disable the bluetooth tracker/proxy if they are not needed
esp32_ble_tracker:
  scan_parameters:
# Adjust timing if the defaults do not work in your environment
#    interval: 1100ms
#    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

switch:
  - platform: gpio
    name: ${name} Relay1
    pin:
      number: GPIO15
      inverted: false
    restore_mode: ${relay1RestoreMode}
    id: relay1
    on_turn_on:
      - light.turn_on: relay1_led
    on_turn_off:
      - light.turn_off: relay1_led
  - platform: gpio
    name: ${name} Relay2
    pin:
      number: GPIO32
      inverted: false
    restore_mode: ${relay2RestoreMode}
    id: relay2
    on_turn_on:
      - light.turn_on: relay2_led
    on_turn_off:
      - light.turn_off: relay2_led
  - platform: restart
    name: ${name} Restart

output:
  - platform: gpio
    pin: GPIO19
    inverted: True
    id: relay1_led_gpio
  - platform: gpio
    pin: GPIO16
    inverted: True
    id: relay2_led_gpio

light:
  - platform: binary
    name: "Relay1 LED"
    id: relay1_led
    restore_mode: RESTORE_DEFAULT_ON
    internal: true    
    output: relay1_led_gpio
  - platform: binary
    name: "Relay2 LED"
    id: relay2_led
    restore_mode: RESTORE_DEFAULT_ON
    internal: true
    output: relay2_led_gpio

sensor:
  - platform: adc
    pin: GPIO34
    name: "${name} LUX"
    update_interval: 10s
    attenuation: 11db
  - platform: hlw8012
    sel_pin:
      number: GPIO25
      inverted: true
    cf_pin: GPIO27
    cf1_pin: GPIO26
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    change_mode_every: 3
    update_interval: 3s    
    current:
      name: "${name} Amps"
      unit_of_measurement: A
      accuracy_decimals: 2
    voltage:
      name: "${name} Volts"
      unit_of_measurement: V
      accuracy_decimals: 1
    power:
      name: "${name} Watts"
      unit_of_measurement: W
      accuracy_decimals: 0    
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - 134 -> 58

binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO18
      mode: INPUT_PULLDOWN
      inverted: True
    name: ${name} Button1
    on_press:
      - switch.toggle: relay1
  - platform: gpio
    internal: true
    pin:
      number: GPIO17
      mode: INPUT_PULLDOWN
      inverted: True
    name: ${name} Button2
    on_press:
      - switch.toggle: relay2

status_led:
  pin:
    number: GPIO5
    inverted: true  
